### ISSUE TITLE
Gleam Plugin Help/Request

### ISSUE THREAD

**Issue by jdrakeford08** [Crowd9/Gleam-Wordpress#1]
Hi, 

my website uses member profiles (creators and brands). I downloaded the plugin and see what it looks like on one of my pages but is there a way for the users (brands) themselves to create their own campaigns that will be posted on the site so that when I go to the "campaign page" you see a catalog of available/active campaigns created by the users?

**Comment by thegyppo** [comment]
The Wordpress plugin only provides a way to insert Shortcodes into your post, we don't offer a way to do this I'm afraid.
